### PR TITLE
Fix PMML Editor CSS

### PR DESCRIPTION
**Pull request by tiagobento**

### CODE REVIEW

**Review by manstis — CHANGES_REQUESTED** [review]
It unfortunately improves things but does not fix them.

The "SampleScorecard" title should not have a border and the text is clipped.

VSIX [built](https://github.com/kiegroup/kie-tooling-store/suites/2298479728/artifacts/48179687) for this PR:-
 
Screenshot from 2021-03-19 16-20-12

VSIX built before webpack change:
Screenshot from 2021-03-19 16-23-22

(The model title only gets a border onHover).

**Comment by tiagobento** [comment]
See https://github.com/kiegroup/kogito-tooling/pull/457

**Review by manstis — APPROVED** [review]
Approving, but I'm not certain this is still required.

**Comment by tiagobento** [comment]
Closing since this was fixed upstream on kogito-tooling.

**Pull request closed without merging**
